// <auto-generated />
using System;
using GotasDaVida.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GotasDaVida.Infrastructure.Migrations
{
    [DbContext(typeof(GotasDaVidaDbContext))]
    [Migration("20260523202714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GotasDaVida.Domain.Entities.Cadastro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("cadastros", (string)null);
                });

            modelBuilder.Entity("GotasDaVida.Domain.Entities.Doadora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bairro");

                    b.Property<Guid>("CadastroId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cadastro_id");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("estado");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("SusNumero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sus_numero");

                    b.Property<bool>("SusPossui")
                        .HasColumnType("bit")
                        .HasColumnName("sus_possui");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId")
                        .IsUnique();

                    b.ToTable("doadoras", (string)null);
                });

            modelBuilder.Entity("GotasDaVida.Domain.Entities.HistoricoGestacional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CadastroId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cadastro_id");

                    b.Property<bool>("Complicacoes")
                        .HasColumnType("bit")
                        .HasColumnName("complicacoes");

                    b.Property<string>("DescricaoComplicacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao_complicacoes");

                    b.Property<int>("NumeroGestacoes")
                        .HasColumnType("int")
                        .HasColumnName("numero_gestacoes");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId")
                        .IsUnique();

                    b.ToTable("historico_gestacional", (string)null);
                });

            modelBuilder.Entity("GotasDaVida.Domain.Entities.SaudeMaterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CadastroId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cadastro_id");

                    b.Property<bool>("CirurgiaRecente")
                        .HasColumnType("bit")
                        .HasColumnName("cirurgia_recente");

                    b.Property<string>("Detalhes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalhes");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("bit")
                        .HasColumnName("diabetes");

                    b.Property<bool>("Hepatite")
                        .HasColumnType("bit")
                        .HasColumnName("hepatite");

                    b.Property<bool>("Hipertensao")
                        .HasColumnType("bit")
                        .HasColumnName("hipertensao");

                    b.Property<bool>("TratamentoMedicoAtivo")
                        .HasColumnType("bit")
                        .HasColumnName("tratamento_medico_ativo");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId")
                        .IsUnique();

                    b.ToTable("saude_materna", (string)null);
                });

            modelBuilder.Entity("GotasDaVida.Domain.Entities.Triagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("AlcoolConsome")
                        .HasColumnType("bit")
                        .HasColumnName("alcool_consome");

                    b.Property<string>("AlcoolFrequencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alcool_frequencia");

                    b.Property<Guid>("CadastroId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cadastro_id");

                    b.Property<int?>("CigarrosPorDia")
                        .HasColumnType("int")
                        .HasColumnName("cigarros_por_dia");

                    b.Property<bool>("Fuma")
                        .HasColumnType("bit")
                        .HasColumnName("fuma");

                    b.Property<bool>("LactacaoAtiva")
                        .HasColumnType("bit")
                        .HasColumnName("lactacao_ativa");

                    b.Property<string>("MedicamentoQual")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medicamento_qual");

                    b.Property<bool>("MedicamentoUsa")
                        .HasColumnType("bit")
                        .HasColumnName("medicamento_usa");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resultado");

                    b.Property<string>("TatuagemMesAno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tatuagem_mes_ano");

                    b.Property<bool>("TatuagemRealizou")
                        .HasColumnType("bit")
                        .HasColumnName("tatuagem_realizou");

                    b.Property<string>("TransfusaoMesAno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transfusao_mes_ano");

                    b.Property<bool>("TransfusaoRealizou")
                        .HasColumnType("bit")
                        .HasColumnName("transfusao_realizou");

                    b.Property<bool>("UsoDrogasIlicitas")
                        .HasColumnType("bit")
                        .HasColumnName("uso_drogas_ilicitas");

                    b.Property<bool>("VacinaDtpa")
                        .HasColumnType("bit")
                        .HasColumnName("vacina_dtpa");

                    b.Property<bool>("VacinaFebreAmarela")
                        .HasColumnType("bit")
                        .HasColumnName("vacina_febre_amarela");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId")
                        .IsUnique();

                    b.ToTable("triagens", (string)null);
                });

            modelBuilder.Entity("GotasDaVida.Domain.Entities.Doadora", b =>
                {
                    b.HasOne("GotasDaVida.Domain.Entities.Cadastro", null)
                        .WithOne("Doadora")
                        .HasForeignKey("GotasDaVida.Domain.Entities.Doadora", "CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GotasDaVida.Domain.Cadastros.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("DoadoraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("email");

                            b1.HasKey("DoadoraId");

                            b1.ToTable("doadoras");

                            b1.WithOwner()
                                .HasForeignKey("DoadoraId");
                        });

                    b.OwnsOne("GotasDaVida.Domain.Cadastros.ValueObjects.Whatsapp", "Whatsapp", b1 =>
                        {
                            b1.Property<Guid>("DoadoraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("whatsapp");

                            b1.HasKey("DoadoraId");

                            b1.ToTable("doadoras");

                            b1.WithOwner()
                                .HasForeignKey("DoadoraId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Whatsapp")
                        .IsRequired();
                });

            modelBuilder.Entity("GotasDaVida.Domain.Entities.HistoricoGestacional", b =>
                {
                    b.HasOne("GotasDaVida.Domain.Entities.Cadastro", null)
                        .WithOne("HistoricoGestacional")
                        .HasForeignKey("GotasDaVida.Domain.Entities.HistoricoGestacional", "CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GotasDaVida.Domain.Entities.SaudeMaterna", b =>
                {
                    b.HasOne("GotasDaVida.Domain.Entities.Cadastro", null)
                        .WithOne("SaudeMaterna")
                        .HasForeignKey("GotasDaVida.Domain.Entities.SaudeMaterna", "CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GotasDaVida.Domain.Entities.Triagem", b =>
                {
                    b.HasOne("GotasDaVida.Domain.Entities.Cadastro", null)
                        .WithOne("Triagem")
                        .HasForeignKey("GotasDaVida.Domain.Entities.Triagem", "CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GotasDaVida.Domain.Entities.Cadastro", b =>
                {
                    b.Navigation("Doadora")
                        .IsRequired();

                    b.Navigation("HistoricoGestacional")
                        .IsRequired();

                    b.Navigation("SaudeMaterna")
                        .IsRequired();

                    b.Navigation("Triagem")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
